# Here, we include connection details for our database environments
duckdb_profile:
  
  target: duckdb # Set DuckDB as the default target
  
  outputs:
    duckdb:
      type: duckdb
      path: ../databases/dev.duckdb
      threads: 3
      attach:
        - path: "postgresql://{{ env_var('POSTGRES_USER') }}:{{ env_var('POSTGRES_PASSWORD') }}@{{ env_var('POSTGRES_HOST') }}:{{ env_var('POSTGRES_PORT') | as_number }}/{{ env_var('POSTGRES_DB') }}"
          alias: postgres_db
          type: postgres
      extensions:
        - httpfs
        - parquet
      settings:
        s3_region: eu-north-1
        s3_access_key_id: "{{ env_var('S3_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('S3_SECRET_ACCESS_KEY') }}"

        
# For reference: https://docs.getdbt.com/reference/dbt-jinja-functions/env_var