sources:
  - name: bronze_parquet_output
    meta:
      external_location: "/workspace/external_ingestion/bronze_parquet_output/{name}.parquet"
    tables:
      - name: customers
      - name: dates
      - name: product_usage
      - name: products
      - name: subscriptions
      - name: support_interactions
